server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: microservicecloud-dept  #自定义服务名称信息
    prefer-ip-address: true  #访问路径可以显示ip地址

spring:
  application:
    name: service-hi

info:
  app.name: tcs-microservicecloud8765
  company.name: www.tcs.com
  build.artifactId: $project.artifactId$
  build.version: $projct.version$