server:
  port: 8765
spring:
  application:
    name: service-eureka

eureka:
  client:
    register-with-eureka: false  #客户端不注册进eureka服务列表内
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


